version: "3.2"

services:
  #NodeJS App
  app:
    build:
      target: prod
    volumes:
      - ./etc/app/.env.prod:/usr/src/app/.env
      #- ./etc/app/ecosystem.config.js:/usr/src/app/ecosystem.config.js